# Generated by Django 4.2.4 on 2023-08-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ourCommunityEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(choices=[('value1', 'Value 1'), ('value2', 'Value 2')], max_length=10)),
            ],
        ),
    ]
