# Generated by Django 4.2.4 on 2023-08-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ourcommunityevents_field1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field1',
            field=models.ImageField(upload_to=None, verbose_name='Image'),
        ),
    ]
