# Generated by Django 4.2.4 on 2023-08-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ourcommunityevents_field1'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcommunityevents',
            name='field2',
            field=models.ImageField(null=True, upload_to='events', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='ourcommunityevents',
            name='field3',
            field=models.ImageField(null=True, upload_to='events', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='ourcommunityevents',
            name='field4',
            field=models.ImageField(null=True, upload_to='events', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='ourcommunityevents',
            name='field5',
            field=models.ImageField(null=True, upload_to='events', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field1',
            field=models.ImageField(null=True, upload_to='events', verbose_name='Image'),
        ),
    ]
