# Generated by Django 4.2.4 on 2023-08-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_course_features_delete_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
