# Generated by Django 4.2.4 on 2023-08-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_features'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
    ]
