# Generated by Django 4.2.4 on 2023-08-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_course_courses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
