# Generated by Django 4.2.4 on 2023-09-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
