# Generated by Django 4.2.4 on 2023-09-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
