# Generated by Django 4.2.4 on 2023-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_applicationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Pending', max_length=10),
        ),
    ]
