# Generated by Django 4.2.4 on 2023-09-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_applicationdetails_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdetails',
            options={'verbose_name': 'Application Details', 'verbose_name_plural': 'Application Details'},
        ),
    ]
