# Generated by Django 4.2.4 on 2023-09-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_applicationdetails_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], max_length=10),
        ),
    ]
