# Generated by Django 4.2.4 on 2023-09-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_applicationdetails_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdetails',
            name='place',
        ),
    ]
