# Generated by Django 4.2.4 on 2023-09-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_applicationdetails_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
