# Generated by Django 4.2.4 on 2023-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_applicationdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationdetails',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='applicationdetails',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field1',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field2',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field3',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field4',
            field=models.ImageField(null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field5',
            field=models.ImageField(null=True, upload_to='events'),
        ),
    ]
