# Generated by Django 4.2.4 on 2023-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_applicationdetails_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='partnerLogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner1', models.ImageField(blank=True, null=True, upload_to='partners')),
                ('partner2', models.ImageField(blank=True, null=True, upload_to='partners')),
                ('partner3', models.ImageField(blank=True, null=True, upload_to='partners')),
            ],
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field1',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field2',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field3',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field4',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='ourcommunityevents',
            name='field5',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
