# Generated by Django 4.2.4 on 2023-09-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_partnerlogos_alter_ourcommunityevents_field1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerlogos',
            options={'verbose_name': 'Partner Logos', 'verbose_name_plural': 'Partner Logos'},
        ),
    ]
