# Generated by Django 4.2.4 on 2023-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_upcomingevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='RecentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Recent Events',
                'verbose_name_plural': 'Recent Events',
            },
        ),
        migrations.AlterModelOptions(
            name='upcomingevent',
            options={'verbose_name': 'Upcoming Event', 'verbose_name_plural': 'Upcoming Event'},
        ),
    ]
